// examples/todo-solid/src/App.jsx
import { createSignal } from "solid-js";
import { store } from './store';
import AddTodo from "./AddTodo";
import TodoItem from "./TodoItem";

const App = () => {
  const [todos, setTodos] = createSignal(store.getItem('todos') || []);
  store.watch('todos', (newTodos) => {
    setTodos(newTodos)
  });

  return (
    <>
      <For each={todos()}>
       {(item, index) => <TodoItem item={item} index={index} />}
      </For>
      <AddTodo />
    </>
  );
};

export default App;

// examples/todo-react/src/App.js
import './App.css';
import { useState } from 'react';
import { store } from './store';
import ButtonCreate from './buttonCreate';
import TodoItem from './TodoItem';

function App() {
  const [todos, setTodos] = useState(store.getItem('todos') || []);
  store.watch('todos', (newTodos) => {
    setTodos(newTodos)
  });

  return (
    <div className="App">
      {
        todos.map((todo, index) => (
          <TodoItem item={todo} index={index} key={index}/>
        ))
      }
      <ButtonCreate total={todos.length} />
    </div>
  );
}

export default App;
